name: Publish arm64

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GH Packages registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build ${{ matrix.service }} for ${{ matrix.os }} Image
        run: |
          docker buildx build --provenance=false --load --platform linux/arm64 -t ghcr.io/${{ github.repository_owner }}/scylla-operator:1.8.0-hotfix -f ./Dockerfile .

      - name: Push to GH Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/scylla-operator:1.8.0-hotfix